### ISSUE TITLE
Feature Request: Style/MutableConstant applied to T.let argument

### ISSUE THREAD

**Issue by dduugg** [Shopify/rubocop-sorbet#35]
The `Style/MutableConstant` [cop](https://docs.rubocop.org/rubocop/cops_style.html#stylemutableconstant) ensures that literal constants (or all constants in `strict` style) are frozen.

However, in a `typed: strict` file, constants must have `T.let` annotations. Sorbet does not recognize `T.let` calls that have`.freeze` appended to them. This largely invalidates the `MutableConstant` cop (since literal constants are wrapped by `T.let` calls, and the latter cannot be frozen).

I would like a sorbet-compatible version of the `Style/MutableConstant` cop. It should require literal first arguments to `T.let` to be frozen with `EnforcedStyle` set to `literals` (the default), or all first arguments when set to `strict`.

Would the maintainers be amenable to such a cop?

**Comment by Morriar** [comment]
👋 Hey @dduugg,

I've been looking at #36 and I think it might not be in the scope of this project.

Our goal with `rubocop-sorbet` is to check that the code is typable and to provide the required autocorrections to make it so. In this particular case I believe the cop is more related to styling than typing.

Also, since `Style/MutableConstant` is a quite popular cop, already used by a lot of people. I think the best course of action would be to either:

1. change Sorbet behaviour so it accepts `Y = T.let(x, X).freeze`
2. change Style/MutableConstant behaviour to it accepts `Y = T.let(x.freeze, X)`

What do you think about bringing this issue to the https://github.com/sorbet/sorbet repository?
